// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompetencyList: typeof import('./components/CompetencyList.vue')['default']
    copy: typeof import('./components/CompetencyList copy.vue')['default']
    DialogDelete: typeof import('./components/DialogDelete.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Modal: typeof import('./components/People/Modal.vue')['default']
    PeopleList: typeof import('./components/PeopleList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
