// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompetencyList: typeof import('./components/CompetencyList.vue')['default']
    List: typeof import('./components/List.vue')['default']
    Modal: typeof import('./components/People/Modal.vue')['default']
    PeopleList: typeof import('./components/List.vue')['default']
    PeopleModal: typeof import('./components/People/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
